### ISSUE TITLE
Unable to download rewind package

### ISSUE THREAD

**Issue by Thanksforhelp** [zhenkewu/rewind#2]
Hi Dr. Zhenke Wu, thanks for this free package and explanation!

I try to download rewind from Github using below r code:

install.packages("devtools",repos="https://cloud.r-project.org")
devtools::install_github("zhenkewu/rewind"),

And below is error rstudio shows:

> devtools::install_github("zhenkewu/rewind")
Downloading GitHub repo zhenkewu/rewind@master
√  checking for file 'C:\Users\Zhaonian\AppData\Local\Temp\Rtmp8ueaiD\remotes294478a61d03\zhenkewu-rewind-d6394a1/DESCRIPTION' ...
-  preparing 'rewind':
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'rewind_0.6.1.tar.gz'
   
Installing package into ‘C:/Users/Zhaonian/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
ERROR: failed to lock directory 'C:/Users/Zhaonian/Documents/R/win-library/3.4' for modifying
Try removing 'C:/Users/Zhaonian/Documents/R/win-library/3.4/00LOCK-rewind'
In R CMD INSTALL
Error: (converted from warning) running command '"C:/PROGRA~1/R/R-34~1.4/bin/x64/R" CMD INSTALL -l "C:\Users\Zhaonian\Documents\R\win-library\3.4" "C:/Users/Zhaonian/AppData/Local/Temp/Rtmp8ueaiD/file29447fab6588/rewind_0.6.1.tar.gz"' had status 3.

Two fo my friends under my request also try to download this package, and they all failed, they have similar error except it is "status 1" or "Non-zero exit status" instead of "status 3".

(converted from warning) installation of package ‘C:/Users/htang/AppData/Local/Temp/Rtmp2d4fHk/file567841645e94/rewind_0.6.1.tar.gz’ had a non-zero exit status

If you could figure what is going on that would be helpful to me, Thanks a lot!

**Comment by zhenkewu** [comment]
@Thanksforhelp I asked Irena (a student of mine who is interested in this method) to reproduce the error. Below is her response - she is using OSX system. Because I currently don't have a windows machine, so if you need to run the package sooner, we can chat. 

This is related to C++ compiler. On a technical note, in the package, I used C code to speed up a few iteration loops to calculate marginal likelihood of data in a cluster. 

"I have tried to reproduce that error that they were running into, but I was not able to reproduce that exact same error. I did however encounter a similar error when trying to install rewind, which also included a "non-zero exit status" message: 
image.png

I was able to fix this by going into the "~/.R/Makevars" file on my computer and changing the CXX = "something something" path to  “CXX=g++”. After this, rewind was able to be installed. I wonder if this is related to their issue? From my understanding, the error I received was because R was able to find the C++ complier. "

**Comment by muschellij2** [comment]
This is due to a failed previous install; you should follow the directions it says:
```
Try removing 'C:/Users/Zhaonian/Documents/R/win-library/3.4/00LOCK-rewind'
```
as that package directory needs to be removed to try installing again.

**Comment by Thanksforhelp** [comment]
Hi Professor Zhenke Wu. Thanks a lot! I would try this way and hope it will
work. Zhaonian.

**Comment by zhenkewu** [comment]
@Thanksforhelp please try again. I just fixed the package.

If you do `?sampler` and copy and paste the example in there, it should run the simulation that recovers the true number of clusters (8) and the true dimension of the latent variables (3).

Problem solved per [here](https://github.com/elbamos/largeVis/issues/5) @muschellij2 

Zhenke

**Comment by Thanksforhelp** [comment]
> This is due to a failed previous install; you should follow the directions it says:
> 
> ```
> Try removing 'C:/Users/Zhaonian/Documents/R/win-library/3.4/00LOCK-rewind'
> ```
> as that package directory needs to be removed to try installing again.



> This is due to a failed previous install; you should follow the directions it says:
> 
> ```
> Try removing 'C:/Users/Zhaonian/Documents/R/win-library/3.4/00LOCK-rewind'
> ```
> as that package directory needs to be removed to try installing again.

Hi @muschellij2, This package works well now. Thanks a lot!
